---
- name: ASA Binary Deployment
  hosts: ASA
  gather_facts: no
  connection: network_cli

  #Author:              Jason A. Sloan
  #Tested OS:           ASA 9.6.4+
  #Tested Models:       5516,5545,5585
  #Tested Modes:        Single Context, Multi Context

  # Known Issue:
  # Due to ASA SSH timeout configuration limitations I am unable to stay connected to the ASA for a period of longer than 60 mins.
  # If the ASA copy operation takes longer than 60 mins, the socket will be forcibly closed by the remote (ASA) side.
  # For this reason smaller binaries are transferred first.
  # The copy operation seems to continue even after the SSH socket is terminated (at least when using tftp).
  # As a workaround you can run the playbook with -t osVerify, sshTimeout to do a verification on the operating system later and reset your SSH timeout

  vars:
          playbook_debug_level: 0
          asaRestVerified: false | bool
          asaAsdmVerified: false | bool
          asaOsVerified: false | bool

  tasks:
  - name: Include SSH Timeout
    include_tasks: helpers/set_max_ssh_timeout.yml
    tags: always

  - name: Include System Context Switch
    include_tasks: helpers/switch_to_system_context.yml
    tags: always

# TODO: Build Smart Deploy for all binaries
# TODO: Check if file exists
# TODO: If File exists, verify.
# TODO: If File Doesn't Exist or Verify Failed, transfer file

########################################################
########################################################
##                    REST API
########################################################
########################################################

  - name: Set Facts for File Exists Helper - REST
    set_fact:
      asaDrive: "disk0"
      asaFile: "{{asaRestImage}}"
    tags: restDeploy
  
  - name: Check if REST exists
    include_tasks: helpers/file_exists.yml
    tags: restDeploy

  - name: Set asaRestExists to File Exists Results
    set_fact:
      asaRestExists: "{{asaFileExists}}"
    tags: restDeploy

  - name: DEBUG - asaRestExists Value
    debug:
      var: asaRestExists
      verbosity: 3
    tags: restDeploy
  
  #TODO: Verification Block
  #Until then set verified to false
  - name: Set REST Verified FALSE
    set_fact:
      asaRestVerified: false
    tags: restDeploy
    #################################
  
  # ASA REST API does not contain embedded signature.
  # asa-restapi-7131-lfbff-k8.SPA
  # MD5: 58a38e1d53f514e631affa33e428f60c
  # SHA-512: 027fd59e2f205a4ba02235c53c7a7f3184b1afc945ca387dcf3cc8732ef3e5b5922fd7d0c5a738b78e4a6630add5699c258a7eb0178cd8ded88d9d53132f776f
  # asa-restapi-132346-lfbff-k8.SPA
  # MD5: e73792f367a60ced5c6b998b258f355a
  # SHA-512: 8397f39051fd9bc3e13f12611f267f1e418639b62eba692bc9fb98bb60f29847c739c88e78b6010ce9afaf1ce5a771bea68ff532d9e1b236a789536b78041a23

#When REST file does not exist or verification failed
  - name: REST Deployment / Re-verification
    block:
      ############### REST COPY OPERATIONS ###############
      - name: Set File Copy Helper Facts
        set_fact: 
          asaDrive: "disk0"
          asaFile: "{{asaRestImage}}"
        tags: restDeploy
    
      - name: Invoke File Copy Helper
        include_tasks: helpers/file_copy.yml
        tags: restDeploy
      ############### END REST COPY ###############

    when: >
      (asaRestExists == false) or
      (asaRestVerified == false)

#
# TODO: Build function to collect wrapped SHA2 signature from REST API and check it.
#


########################################################
########################################################
##                       ASDM
########################################################
########################################################


# ASDM Smart Deploy (Copy only if file doesn't exist or fails verify)
############### IMAGE EXISTS ######################
  - name: Set Facts for File Exists Helper - ASDM
    set_fact:
      asaDrive: "disk0"
      asaFile: "{{asaAsdmImage}}"
    tags: asdmDeploy
  
  - name: Check if File Exists
    include_tasks: helpers/file_exists.yml
    tags: asdmDeploy

  - name: Set asaAsdmExists to File Exists Results
    set_fact:
      asaAsdmExists: "{{asaFileExists}}"
    tags: asdmDeploy

  - name: asaAsdmExists Value
    debug:
      var: asaAsdmExists
      verbosity: 3
    tags: asdmDeploy

###################################################
# Run verify on ASDM image if it exists
  - name: Tasks When ASDM Image Exists
    block:
      - name: Include ASDM Verification
        include_tasks: helpers/asdm_verify.yml
        tags: asdmDeploy
    when: asaAsdmExists == true
    tags: asdmDeploy

# When ASDM Does Not Exist or Verification Failed.
  - name: ASDM Deployment / Re-Verification
    block:
      ############### ASDM COPY OPERATIONS ###############
      - name: Set File Copy Helper Facts - ASDM
        set_fact: 
          asaDrive: "disk0"
          asaFile: "{{asaAsdmImage}}"
        tags: asdmDeploy
    
      - name: Invoke File Copy Helper
        include_tasks: helpers/file_copy.yml
        tags: asdmDeploy
      ############### END ASDM COPY ###############

      - name: ASDM Verify
        include_tasks: helpers/asdm_verify.yml
        tags: asdmDeploy

      # TODO: Build in validation from calculated checksum against stored variable.
      # TODO: Last ditch effort to verify.
      # TODO: Will require getting checksums from Cisco Website for images.

    ############### END ASDM IMAGE VERIFY ###############
    when: >
      (asaAsdmExists == false) or
      (asaAsdmVerified == false)

########################################################
########################################################
##                  OPERATING SYSTEM
########################################################
########################################################

# Operating System Smart Deploy (Copy only if file doesn't exist or fails verify)
############### IMAGE EXISTS ######################
  - name: Set File Exists Helper Facts - OS
    set_fact:
      asaDrive: "disk0"
      asaFile: "{{asaOsImage}}"
    tags: osDeploy
  
  - name: Check if File Exists
    include_tasks: helpers/file_exists.yml
    tags: osDeploy

  - name: Set asaOsExists to File Exists Results
    set_fact:
      asaOsExists: "{{asaFileExists}}"
    tags: osDeploy

  - name: asaOsExists Value
    debug:
      var: asaOsExists
      verbosity: 3
    tags: osDeploy
###################################################

############### IMAGE VERIFY ###############
  - name: Tasks When OS Image Exists
    block:
      - name: Include OS Verification
        include_tasks: helpers/os_verify.yml
        tags: osDeploy
    when: asaOsExists == true
###################################################

#When OS Image Does Not Exist or Verification Failed
  - name: OS Copy Block
    block:
    ############## OS COPY OPERATIONS #################
    - name: Set File Copy Helper Facts - OS
      set_fact:
        asaDrive: "disk0"
        asaFile: "{{asaOsImage}}"
      tags: osDeploy

      - name: Invoke File Copy Helper
        include_tasks: helpers/file_copy.yml
        tags: osDeploy
      ############### END OS COPY ###############

      ############### VERIFY OS #################
      - name: OS Verify After Copy
        include_tasks: helpers/os_verify.yml
        tags: osDeploy
      ############### END OS VERIFY #############

    when: >
      (asaOsExists == false) or
      (asaOsVerified == false)

  - name: Exit System Context
    include_tasks: helpers/exit_system_context.yml
    tags: always

  - name: Restore SSH to default
    include_tasks: helpers/set_ssh_timeout_to_default.yml
    tags: always