---
- name: ASA ASDM Deployment / Configuration
  hosts: ASA_PRIMARY
  gather_facts: no
  connection: network_cli

  #Author:              Jason A. Sloan
  #Tested OS:           ASA 9.6.4+
  #Tested Models:       5516,5545,5585
  #Tested Modes:        Single Context, Multi Context

  # Requires: defined asaAsdmImage variable (recommend defining in inventory).

  # This playbook will check to see if the ASDM file specified by asaAsdmImage exists.
  # If the image exists it will verify it, and if verified it will set the image as the
  # current ASDM image and save the configuration.

  # Options (passed as extra_var):
  # AsdmCopy=true to copy the ASDM file to the ASA if it does not exist on box.
  # DANGER: In failover configuration this could result in mate not having appropriate image.
  # TODO: determine failover status and execute copy command on mate if applicable.

  # AsdmClean=true to cleanup unused ASDM images
  # TODO: determine failover status and cleanup on mate if applicable.

  vars:
          playbook_debug_level: 0
          asaAsdmVerified: false | bool
          asaAsdmCopy: "{{ AsdmCopy | default(false) | bool }}"
          asaAsdmClean: "{{ AsdmClean | default(false) | bool }}"

  tasks:
  - name: Include SSH Timeout
    include_tasks: helpers/set_max_ssh_timeout.yml
    tags: always

  - name: Include System Context Switch
    include_tasks: helpers/switch_to_system_context.yml
    tags: always
  
  - name: asaAsdmCopy Value
    debug:
      var: asaAsdmCopy
      verbosity: 3
    tags: asdmFact

############### RECORD CURRENT ASDM ###############
  - name: Get ASDM Setting
    asa_command:
      commands:
        - show asdm image
    register: _asdmShow
    vars:
      ansible_command_timeout: 180
    tags: asdmFact

  - name: Debug ASDM Show
    debug:
      var: _asdmShow
      verbosity: 3
    when: _asdmShow is failed
    tags: asdmFact
###################################################

############### SHOW CURRENT ASDM #################
  - name: Set Fact - ASDM Image
    set_fact:
      asaCurrentAsdm: "{{ _asdmShow.stdout[0].split('/')[-1]|trim }}"
    tags: asdmFact

  - name: Display current ASDM Version
    debug:
      var: asaCurrentAsdm
    when:
      - asaCurrentAsdm | length > 0
      - asaCurrentAsdm is defined
    tags: asdmFact
###################################################

  - name: Set facts for file helpers - ASDM
    set_fact:
      asaDrive: "disk0"
      asaFile: "{{asaAsdmImage}}"
    tags: always

############### IMAGE EXISTS ######################
  - name: Check ASDM Image Exists
    include_tasks: helpers/file_exists.yml
    tags: asdmFact

  - name: Set asaAsdmExists value to asaFileExists value
    set_fact:
      asaAsdmExists: "{{asaFileExists}}"
    when:
      - asaFileExists is defined
    tags: asdmFact

  - name: asaAsdmExists Value
    debug:
      var: asaAsdmExists
      verbosity: 3
    tags: asdmFact
###################################################

################## COPY IMAGE #####################
  - name: Copy ASDM Image if not existent.
    include_tasks: helpers/file_copy.yml
    when:
      - asaAsdmExists == false
      - asaAsdmCopy == true
    tags: asdmCopy

  - name: Set EXISTS to true if successful
    set_fact:
      asaAsdmExists: true
    when: _asaFileCopy is success
###################################################

################# VERIFY IMAGE ####################
  - name: Tasks when image exists
    block:
      - name: File Validation
        include_tasks: helpers/file_verify.yml
        tags: asdmFact

      - name: Set Verified to asaFileVerified value
        set_fact:
          asaAsdmVerified: "{{asaFileVerified}}"
        tags: asdmFact
    when: asaAsdmExists == true
###################################################

############ ASDM Configuration Block #############
  - name: ASDM Configuration Block
    block:   
      ################# SET ASDM IMAGE ####################
      - name: Set ASDM Image - asdm image {{asaDrive}}:/{{ asaAsdmImage }}
        asa_config:
          lines:
            - asdm image {{asaDrive}}:/{{ asaAsdmImage }}
        register: _asdmConfig
        when:
          - asaAsdmVerified == true
          - asaCurrentAsdm != asaAsdmImage
        vars:
          ansible_command_timeout: 180
        tags: asdmConfig
    
      - name: DEBUG - Failed Configuration
        debug:
          var: _asdmConfig
        when: >
          (playbook_debug_level > 3) or
          (_asdmConfig is failed)
        tags: asdmConfig


      ###################### ASDM Cleanup #########################
      - name: Cleanup old ASDM Image
        block:
          - name: List ASDM Images
            asa_command:
              commands:
                - dir {{asaDrive}}:/asdm-[0-9]*.bin
            register: _asaAsdmInventory
            vars:
              ansible_command_timeout: 180
            tags: asdmClean

          - name: Gather Image Filenames
            set_fact:
              asaAsdmInventory: "{{ asaAsdmInventory|default([]) + [item.split()[-1]] }}"
            when: item.split() | length == 8
            with_items:
              - "{{ _asaAsdmInventory.stdout_lines[0] }}"
            tags: asdmClean

          - name: Delete ASDM Images
            asa_command:
              commands:
                - delete /noconfirm disk0:/{{ item }}
                - failover exec mate delete /noconfirm disk0:/{{ item }}
            when:
              - item.split()[-1] != asaAsdmImage
            vars:
              ansible_command_timeout: 180
            with_items:
              - "{{ asaAsdmInventory }}"
            tags: asdmClean
        when:
          - _asdmConfig is success
          - asaAsdmClean == true
      #############################################################

      - name: Save [SYSTEM] Context Configuration
        include_tasks: helpers/save_configuration.yml
        when: asaMulticontext == "true"
        tags: always

###################################################

############### END BLOCK CONDITIONAL #############
    when: asaAsdmExists == true
###################################################

  - name: Exit System Context
    include_tasks: helpers/exit_system_context.yml
    tags: always

  - name: Restore SSH to default
    include_tasks: helpers/set_ssh_timeout_to_default.yml
    tags: always

  - name: Save Configuration
    include_tasks: helpers/save_configuration.yml
    tags: always
